---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[scout::scout-install]
      - recipe[scout::scout-cron]
#      - recipe[scout::scout-cron-delete]
    attributes:
